const cases=[];
const add=(name,source,files={},entry='main.scss')=>cases.push({name,entry,files:{[entry]:source,...files}});
const tokens='$size: 4px !default; $color: red !default; $_secret: 8; @function twice($x: $size){@return $x * 2} @mixin card($x: $size){width:$x;color:$color} .tokens{x:$size}';
add('namespace-variable-function-mixin','@use "tokens";.a{x:tokens.$size;y:tokens.twice();@include tokens.card(9px)}',{'_tokens.scss':tokens});
add('alias','@use "tokens" as t;.a{x:t.$size;y:t.twice();@include t.card}',{'tokens.scss':tokens});
add('star','@use "tokens" as *;.a{x:$size;y:twice();@include card}',{'_tokens.scss':tokens});
add('module-lexical-scope','$size:99px;@use "tokens";.a{y:tokens.twice()}',{'_tokens.scss':tokens});
add('module-cannot-see-caller','$size:99px;@use "tokens";',{'_tokens.scss':'.x{v:$size}'});
add('nested-relative','@use "styles/theme";.a{x:theme.$n}',{'styles/_theme.scss':'@use "../common";$n:common.$n * 2;','_common.scss':'$n:3px;.base{x:1}'});
add('index','@use "theme";.a{x:theme.$n}',{'theme/_index.scss':'$n:6'});
add('index-explicit','@use "theme/index";.a{x:index.$n}',{'theme/_index.scss':'$n:6'});
add('normalization','@use "./theme/../tokens.scss";.a{x:tokens.$size}',{'tokens.scss':tokens});
add('underscore-url','@use "_tokens";.a{x:tokens.$size}',{'_tokens.scss':tokens});
add('extension-alias','@use "tokens.scss" as t;.a{x:t.$size}',{'tokens.scss':tokens});
add('configure','@use "tokens" with ($size:7px,$color:blue);.a{y:tokens.twice();@include tokens.card}',{'_tokens.scss':tokens});
add('configure-expression','$base:2;@use "tokens" with ($size:$base * 3px);.a{x:tokens.$size}',{'_tokens.scss':tokens});
add('configure-null','@use "tokens" with ($size:null);.a{x:tokens.$size}',{'_tokens.scss':tokens});
add('configure-missing','@use "tokens" with ($missing:2);',{'_tokens.scss':tokens});
add('configure-nondefault','@use "tokens" with ($n:2);',{'_tokens.scss':'$n:1'});
add('configure-private','@use "tokens" with ($_secret:2);',{'_tokens.scss':tokens});
add('configure-twice','@use "tokens" as a with ($size:2px);@use "tokens" as b with ($size:3px);',{'_tokens.scss':tokens});
add('duplicate-load-alias','@use "tokens" as a;@use "./_tokens.scss" as b;.x{a:a.$size;b:b.$size}',{'_tokens.scss':tokens});
add('diamond-load-once','@use "a";@use "b";.x{a:a.$n;b:b.$n}',{'a.scss':'@use "shared";$n:shared.$n;.a{x:1}','b.scss':'@use "shared";$n:shared.$n;.b{x:1}','_shared.scss':'$n:7;.shared{x:1}'});
add('mutation-shared','@use "tokens" as a;@use "tokens" as b;a.$size:10px;.x{x:b.$size;y:b.twice()}',{'_tokens.scss':tokens});
add('mutation-nested','@use "tokens" as a;.x{a.$size:10px;y:a.twice()}.y{x:a.$size}',{'_tokens.scss':tokens});
add('mutation-star','@use "tokens" as *;$size:12px;.x{x:twice()}',{'_tokens.scss':tokens});
add('private-variable','@use "tokens";.a{x:tokens.$_secret}',{'_tokens.scss':tokens});
add('private-function','@use "lib";.a{x:lib.-f()}',{'lib.scss':'@function -f(){@return 1}'});
add('private-mixin','@use "lib";.a{@include lib._m}',{'lib.scss':'@mixin _m(){x:1}'});
add('undefined-variable','@use "tokens";.a{x:tokens.$missing}',{'_tokens.scss':tokens});
add('undefined-namespace','.a{x:missing.$n}');
add('undefined-mixin','@use "tokens";.a{@include tokens.missing}',{'_tokens.scss':tokens});
add('undefined-function','@use "tokens";.a{x:tokens.missing()}',{'_tokens.scss':tokens});
add('undefined-mutation','@use "tokens";tokens.$missing:2;',{'_tokens.scss':tokens});
add('std-constants','@use "sass:math";.a{pi:math.$pi;e:math.$e;eps:math.$epsilon;max:math.$max-safe-integer}');
add('std-constant-alias','@use "sass:math" as m;.a{x:m.$pi}');
add('std-readonly','@use "sass:math";math.$pi:3;');
add('same-namespace','@use "a";@use "dir/a";',{'a.scss':'','dir/a.scss':''});
add('std-namespace-collision','@use "sass:math";@use "math";',{'math.scss':''});
add('use-after-css','.x{x:1}@use "a";',{'a.scss':''});
add('use-after-function','@function f(){@return 1}@use "a";',{'a.scss':''});
add('nested-use','.x{@use "a";}',{'a.scss':''});
add('missing-file','@use "missing";');
add('ambiguous-partial','@use "a";',{'a.scss':'$n:1','_a.scss':'$n:2'});
add('ambiguous-index','@use "a";',{'a/index.scss':'$n:1','a/_index.scss':'$n:2'});
add('file-before-index','@use "a";.x{x:a.$n}',{'a.scss':'$n:1','a/_index.scss':'$n:2'});
add('direct-cycle','@use "a";',{'a.scss':'@use "a";'});
add('indirect-cycle','@use "a";',{'a.scss':'@use "b";','b.scss':'@use "a";'});
add('forward-all','@use "api";.a{x:api.$size;y:api.twice();@include api.card}',{'api.scss':'@forward "tokens";','_tokens.scss':tokens});
add('forward-not-visible-locally','@use "api";',{'api.scss':'@forward "tokens";.a{x:$size}','_tokens.scss':tokens});
add('forward-plus-use','@use "api";.a{x:api.$n}',{'api.scss':'@forward "tokens";@use "tokens";$n:tokens.$size;','_tokens.scss':tokens});
add('forward-prefix','@use "api";.a{x:api.$ui-size;y:api.ui-twice();@include api.ui-card}',{'api.scss':'@forward "tokens" as ui-*;','_tokens.scss':tokens});
add('forward-show','@use "api";.a{x:api.$size;y:api.twice()}',{'api.scss':'@forward "tokens" show $size, twice;','_tokens.scss':tokens});
add('forward-show-excluded','@use "api";.a{@include api.card}',{'api.scss':'@forward "tokens" show $size, twice;','_tokens.scss':tokens});
add('forward-hide','@use "api";.a{x:api.$size;@include api.card}',{'api.scss':'@forward "tokens" hide $color, twice;','_tokens.scss':tokens});
add('forward-hide-excluded','@use "api";.a{x:api.twice()}',{'api.scss':'@forward "tokens" hide $color, twice;','_tokens.scss':tokens});
add('forward-prefix-show-original','@use "api";.a{x:api.$ui-size}',{'api.scss':'@forward "tokens" as ui-* show $size;','_tokens.scss':tokens});
add('forward-prefix-show-prefixed','@use "api";.a{x:api.$ui-size}',{'api.scss':'@forward "tokens" as ui-* show $ui-size;','_tokens.scss':tokens});
add('forward-mutation','@use "api";@use "tokens";api.$size:20px;.a{x:tokens.$size;y:api.twice()}',{'api.scss':'@forward "tokens";','_tokens.scss':tokens});
add('forward-chain','@use "api";.a{x:api.$size}',{'api.scss':'@forward "middle";','middle.scss':'@forward "tokens";','_tokens.scss':tokens});
add('forward-duplicate-same-origin','@use "api";.a{x:api.$size}',{'api.scss':'@forward "tokens";@forward "middle";','middle.scss':'@forward "tokens";','_tokens.scss':tokens});
add('forward-conflict-variable','@use "api";',{'api.scss':'@forward "a";@forward "b";','a.scss':'$n:1','b.scss':'$n:2'});
add('forward-conflict-function','@use "api";',{'api.scss':'@forward "a";@forward "b";','a.scss':'@function f(){@return 1}','b.scss':'@function f(){@return 2}'});
add('forward-explicit-config','@use "api";.a{x:api.$size}',{'api.scss':'@forward "tokens" with ($size:5px);','_tokens.scss':tokens});
add('forward-incoming-config','@use "api" with ($size:5px);.a{x:api.$size}',{'api.scss':'@forward "tokens";','_tokens.scss':tokens});
add('forward-prefix-config','@use "api" with ($ui-size:5px);.a{x:api.$ui-size}',{'api.scss':'@forward "tokens" as ui-*;','_tokens.scss':tokens});
add('forward-default-config','@use "api" with ($size:5px);.a{x:api.$size}',{'api.scss':'@forward "tokens" with ($size:8px !default);','_tokens.scss':tokens});
add('forward-default-used','@use "api";.a{x:api.$size}',{'api.scss':'@forward "tokens" with ($size:8px !default);','_tokens.scss':tokens});
add('star-conflict-variable','@use "a" as *;@use "b" as *;.x{x:$n}',{'a.scss':'$n:1','b.scss':'$n:2'});
add('star-conflict-unused','@use "a" as *;@use "b" as *;.x{x:1}',{'a.scss':'$n:1','b.scss':'$n:2'});
add('star-conflict-function','@use "a" as *;@use "b" as *;.x{x:f()}',{'a.scss':'@function f(){@return 1}','b.scss':'@function f(){@return 2}'});
add('star-same-forwarded-origin','@use "a" as *;@use "b" as *;.x{x:$n;y:f()}',{'a.scss':'@forward "shared";','b.scss':'@forward "shared";','shared.scss':'$n:1;@function f(){@return 2}'});
add('star-local-var-before','$n:9;@use "a" as *;.x{x:$n}',{'a.scss':'$n:1'});
add('star-local-var-after','@use "a" as *;$n:9;.x{x:$n}',{'a.scss':'$n:1'});
add('star-local-function','@use "a" as *;@function f(){@return 9}.x{x:f()}',{'a.scss':'@function f(){@return 1}'});
add('diagnostics','@use "a";@warn "entry";.a{x:1}',{'a.scss':'@debug "library";'});
add('configuration-applies-once','@use "a" with ($n:2);.x{x:a.$n}',{'a.scss':'$n:1 !default;$n:7;$n:3 !default;'});
add('configuration-after-normal-declaration','@use "a" with ($n:2);.x{x:a.$n}',{'a.scss':'$n:7;$n:3 !default;'});
add('forward-config-chain','@use "a" with ($n:2);.x{x:a.$n}',{'a.scss':'@forward "b";','b.scss':'@forward "c";','c.scss':'$n:1 !default;'});
add('forward-config-siblings','@use "a" with ($x:2,$y:3);.x{x:a.$x;y:a.$y}',{'a.scss':'@forward "b";@forward "c";','b.scss':'$x:1 !default;','c.scss':'$y:1 !default;'});
add('forward-config-local-default','@use "a" with ($x:2,$y:3);.x{x:a.$x;y:a.$y}',{'a.scss':'@forward "b";$y:1 !default;','b.scss':'$x:1 !default;'});
add('forward-config-hidden','@use "a" with ($x:2);.x{x:a.$x}',{'a.scss':'@forward "b" hide $x;','b.scss':'$x:1 !default;'});
add('forward-config-show','@use "a" with ($x:2);.x{x:a.$x}',{'a.scss':'@forward "b" show $x;','b.scss':'$x:1 !default;'});
add('forward-config-fixed-override','@use "a" with ($x:2);',{'a.scss':'@forward "b" with ($x:1);','b.scss':'$x:0 !default;'});
add('forward-config-unknown-explicit','@use "a";',{'a.scss':'@forward "b" with ($z:1);','b.scss':'$x:0 !default;'});
add('forward-own-override','@use "a";.x{x:a.$n}',{'a.scss':'@forward "b";$n:2;','b.scss':'$n:1;'});
add('forward-css-before-parent','@use "a";.x{x:3}',{'a.scss':'@forward "b";.a{x:2}','b.scss':'.b{x:1}'});
add('forward-after-css','.a{x:1}@forward "b";',{'b.scss':'.b{x:2}'});
add('forward-private-not-exported','@use "a";.x{x:a.$-n}',{'a.scss':'@forward "b";','b.scss':'$-n:1;'});
add('standard-name-hyphens','@use "a";.x{x:a.$foo_bar;y:a.foo_bar()}',{'a.scss':'$foo-bar:1;@function foo-bar(){@return 2}'});
add('nested-namespace-function','@use "a";.x{x:a.f(3)}',{'a.scss':'@use "b";@function f($n){@return b.g($n)}','b.scss':'$n:2;@function g($v){@return $v*$n}'});
add('star-local-shadow-rule','@use "a" as *;.x{$n:8;x:$n}.y{x:$n}',{'a.scss':'$n:1;'});
add('star-mutation-from-function','@use "a" as *;@function f(){$n:8 !global;@return $n}.x{x:f();y:$n}',{'a.scss':'$n:1;'});
add('index-resolution-local','@use "a";.x{x:a.$n}',{'a/_index.scss':'@use "b";$n:b.$n;','a/_b.scss':'$n:9;'});
add('use-configuration-default-flag','@use "a" with ($n:2 !default);',{'a.scss':'$n:1 !default;'});
add('forward-private-prefix','@use "a";.x{x:a.$-n}',{'a.scss':'@forward "b" as -*;','b.scss':'$n:1;'});
add('diagnostics-in-function','@function f(){@warn "f";@debug 1 + 2;@return 4}.x{x:f()}');
add('underscore-namespace','@use "some_tokens";.x{x:some_tokens.$foo_bar;y:some_tokens.foo_bar();@include some_tokens.card}',{'_some_tokens.scss':'$foo-bar:2;@function foo-bar(){@return 3}@mixin card(){width:4px}'});
add('underscore-alias','@use "a" as foo_bar;foo_bar.$n:3;.x{x:foo_bar.$n}',{'a.scss':'$n:1'});
add('namespace-underscore-is-distinct','@use "a" as foo_bar;.x{x:foo-bar.$n}',{'a.scss':'$n:1'});
add('standard-underscore-alias','@use "sass:math" as my_math;.x{x:my_math.div(6,2);y:my_math.$pi}');
export default cases;
