const sources=[
 '.base{color:red}.button{@extend .base}',
 '.button{@extend .base}.base{color:red}',
 '%base{color:red}.button{@extend %base}',
 '%unused{color:red}.button{color:blue}',
 '.base,.other{color:red}.button{@extend .base}',
 '.base{color:red}.a,.b{@extend .base}',
 '.base{color:red}.a{@extend .base}.b{@extend .a}',
 '.a{@extend .b}.b{@extend .c}.c{color:red}',
 '.base:hover{color:red}.button{@extend .base}',
 '.base::before{color:red}.button{@extend .base}',
 '.base.active{color:red}.button{@extend .base}',
 '.base.active{color:red}.button.large{@extend .base}',
 'a.base{color:red}.button{@extend .base}',
 '.base{color:red}a.button{@extend .base}',
 'a.base{color:red}button.other{@extend .base}',
 '.base[data-label=".base"]{color:red}.button{@extend .base}',
 '.base-2{color:red}.button{@extend .base !optional}',
 '.a{color:red}.a{@extend .a}',
 '.a{color:red}.b{@extend .a}.a{@extend .b}',
 '.parent .base{color:red}.button{@extend .base}',
 '.parent .base{color:red}.scope .button{@extend .base}',
 '.parent .base{color:red}.parent .button{@extend .base}',
 '.parent > .base{color:red}.button{@extend .base}',
 '.base .base{color:red}.button{@extend .base}',
 '.a{}.b{@extend .a}',
 '.a{color:red}.b{@extend .missing !optional;color:blue}',
 '.a{color:red}.b{@extend .missing}',
 '@extend .a;',
 '.a{color:red}.b{@extend .a.c}',
 '.a{color:red}.b{@extend .a .c}',
 '.a{color:red}.b{@extend &}',
 '.a,.c{color:red}.b{@extend .a,.c}',
 '@media screen{.base{color:red}.button{@extend .base}}',
 '@media screen{.base{color:red}}.button{@extend .base}',
 '.base{color:red}@media screen{.button{@extend .base}}',
 '@supports(display:grid){.base{color:red}}.button{@extend .base}',
 '@mixin base(){@extend %base}%base{color:red}.button{@include base()}',
 '$target:base;.base{color:red}.button{@extend .#{$target}}',
 '.a{color:red;@at-root .b{color:blue}color:green}',
 '.a{@at-root{.b{color:red}}}',
 '.a{@at-root{.b &{color:red}}}',
 '.a{@at-root .b &{color:red}}',
 '.a{@at-root #{&}{color:red}}',
 '.a{@at-root{color:red}}',
 '.a{@at-root .b{.c{color:red}}}',
 '@media screen{.a{@at-root .b{color:red}}}',
 '@media screen{.a{@at-root(without:media){color:red}}}',
 '@media screen{.a{@at-root(without:rule){.b{color:red}}}}',
 '@media screen{.a{@at-root(without:all){.b{color:red}}}}',
 '@media screen{.a{@at-root(with:rule){color:red}}}',
 '@media screen{@supports(display:grid){.a{@at-root(with:media){.b{color:red}}}}}',
 '@media screen{.a{color:red;@at-root(without:media){color:blue}color:green}}',
 '.a{@at-root(with:all){color:red}}',
 '.a{@at-root(without:rule media){.b{color:red}}}',
 '.a{@at-root(bad:rule){color:red}}',
 '.a{@at-root(without:){color:red}}',
 '@mixin lift(){@at-root .lifted{color:red}}.a{@include lift()}',
 '%base{color:red}.a{@at-root .b{@extend %base}}',
 '.a{color:red}.b{@at-root .c{@extend .a}}',
 '.a{.base{color:red}.button{@extend .base}}',
];
const cases=sources.map((source,i)=>({name:`selector-${i+1}`,source}));
cases.push(
 {name:'module-extension',entry:'main.scss',files:{'main.scss':'@use "base";.button{@extend %base}', '_base.scss':'%base{color:red}'}},
 {name:'module-class-extension',entry:'main.scss',files:{'main.scss':'@use "base";.button{@extend .base}', '_base.scss':'.base{color:red}'}},
 {name:'private-placeholder',entry:'main.scss',files:{'main.scss':'@use "base";.button{@extend %-base}', '_base.scss':'%-base{color:red}'}},
 {name:'private-placeholder-optional',entry:'main.scss',files:{'main.scss':'@use "base";.button{@extend %-base !optional}', '_base.scss':'%-base{color:red}'}},
 {name:'sibling-isolation',entry:'main.scss',files:{'main.scss':'@use "a";@use "b";', '_a.scss':'.base{color:red}', '_b.scss':'.button{@extend .base}'}},
 {name:'transitive-module',entry:'main.scss',files:{'main.scss':'@use "b";', '_a.scss':'.base{color:red}', '_b.scss':'@use "a";.button{@extend .base}'}},
 {name:'forwarded-module',entry:'main.scss',files:{'main.scss':'@use "b";.button{@extend %base}', '_a.scss':'%base{color:red}', '_b.scss':'@forward "a";'}},
 {name:'module-cannot-extend-downstream',entry:'main.scss',files:{'main.scss':'@use "base";.button{color:red}', '_base.scss':'.other{@extend .button !optional}'}},
 {name:'module-mixin-private-extension',entry:'main.scss',files:{'main.scss':'@use "base";.button{@include base.m()}', '_base.scss':'%-base{color:red}@mixin m(){@extend %-base}'}},
 {name:'empty-lifted-target',source:'.outer{@at-root .base{}}.button{@extend .base}'},
);
export default cases;
